### PR TITLE
ApiException mutable field better encapsulation

### LINKED ISSUE #654: [Questions] On `ApiException` design
Hi there 👋 !

I'm digging down a bit in the codebase and I have a couple of questions regarding the design of `ApiException` and how you envision its interaction with Authentication mechanisms:

1. [`requestStatusCode`](https://github.com/microsoft/kiota-java/blob/f41fcfefa7eb119f1e680b0e1bca3cd36c11660b/components/abstractions/src/main/java/com/microsoft/kiota/ApiException.java#L27) is a public mutable field, which seems odd, once the Exception is thrown we want the `statusCode` to be a stable number that cannot be easily changed in user code.
2. `ApiException` is a ["checked exception"](https://github.com/microsoft/kiota-java/blob/f41fcfefa7eb119f1e680b0e1bca3cd36c11660b/components/abstractions/src/main/java/com/microsoft/kiota/ApiException.java#L8) which means that it should be explicitly written in all the method signatures using it. There are quite some discussions around checked exceptions in Java, but, in this context, how do I throw an `ApiException(401)` from an `AuthenticationProvider` so that it's indistinguishable from a business logic 401 handled at the API level?

### PR DESCRIPTION
**Pull request by andreaTP**
fixes #654 , using a builder pattern we can better encapsulate the `responseStatusCode` mutable field.

I think it's a code smell to pass to the user-land an object with a mutable field, since we have all of the information to build the final one it should not be exposed to the user.

### CODE REVIEW

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiException.java [hunk 1]
```diff
@@ -24,7 +24,25 @@ public ApiException(@Nonnull final Throwable cause) {
...
+    public int getResponseStatusCode() {
+        return responseStatusCode;
+    }
+
+    /**
+     * Sets the HTTP response status code
+     * @param responseStatusCode The response status code to set.
+     */
+    protected void setResponseStatusCode(int responseStatusCode) {
+        Objects.requireNonNull(responseStatusCode);
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiException.java:43]:
```suggestion
```
int's can't be null? or does this method also check for 0 ?

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+import java.util.Objects;
+
+/** Builder class for ApiException. */
+public class ApiExceptionBuilder {
+
+    private ApiException value = null;
+    public ApiExceptionBuilder() {
+    }
+    public ApiExceptionBuilder(ApiException base) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:13]: all methods in this class are missing doc comments

File: components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java [hunk 3]
```diff
@@ -611,24 +614,29 @@ private Response throwIfFailedResponse(@Nonnull final Response response, @Nonnul
...
                 }
                 spanForAttributes.setAttribute(errorBodyFoundAttributeName, true);
                 final Span deserializationSpan = GlobalOpenTelemetry.getTracer(obsOptions.getTracerInstrumentationName()).spanBuilder("getObjectValue").setParent(Context.current().with(span)).startSpan();
                 try(final Scope deserializationScope = deserializationSpan.makeCurrent()) {
                     final Parsable error = rootNode.getObjectValue(errorClass);
-                    ApiException result;
+                    ApiExceptionBuilder resultBuilder;
                     if (error instanceof ApiException) {
-                        result = (ApiException)error;
+                        resultBuilder = new ApiExceptionBuilder((ApiException)error);
```
Comment (baywet) [inline components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java:631]: I'm not sure about that last change. We'd effectively be wrapping all exceptions in a parent Api exception. Since all exceptions inherit from API exception, this seems superfluous, and will create confusion: which object contains the headers and status code from a consumer perspective?

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiException.java (hunk 1 above)
Comment (andreaTP) [reply components/abstractions/src/main/java/com/microsoft/kiota/ApiException.java:43]: no they cannot be null you are right

File: components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java (hunk 3 above)
Comment (andreaTP) [reply components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java:631]: > We'd effectively be wrapping all exceptions in a parent Api exception.

why? here we only pass through a Builder pattern to keep the final object immutable for the user, that's it.
This change is mostly cosmetics and doesn't alter the original behavior (AFAIU).

> which object contains the headers and status code from a consumer perspective?

The final `ApiException` returned to the user.

Have I missed any invariant here?

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java (hunk 2 above)
Comment (andreaTP) [reply components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:21]: done

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+    /**
+     * Constructs an empty ApiExceptionBuilder
+     */
+    public ApiExceptionBuilder() {
+    }
+
+    /**
+     * Constructs an ApiExceptionBuilder starting from a base ApiException
+     */
+    public ApiExceptionBuilder(ApiException base) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:21]: missing doc comment for the parameter

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+        value = base;
+    }
+
+    /**
+     * Assign the message to the builder
+     * @return The builder object.
+     */
+    public ApiExceptionBuilder withMessage(@Nonnull String message) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:29]: missing doc comment for the parameter (for all methods)

File: components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java (hunk 3 above)
Comment (baywet) [reply components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java:631]: right, I missed a subtility in the builder implementation. Disregard.

**Review by baywet — CHANGES_REQUESTED** [review]

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java (hunk 5 above)
Comment (andreaTP) [reply components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:31]: done, hopefully 🤞

**Review by baywet — DISMISSED** [review]
Thanks for making the changes!

**Review by baywet — APPROVED** [review]

**Comment by andreaTP** [comment]
Fixed, if you want the Changelog entry, just merge first the other PR and I'll follow up.

**Comment by andreaTP** [comment]
should be ready now 👍

**Review by baywet — DISMISSED** [review]

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+     * Constructs an empty ApiExceptionBuilder
+     */
+    public ApiExceptionBuilder() {
+    }
+
+    /**
+     * Constructs an ApiExceptionBuilder starting from a base ApiException
+     * @param base The original ApiException to be used as a base.
+     */
+    public ApiExceptionBuilder(ApiException base) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:22]:
```suggestion
    public ApiExceptionBuilder(@Nonnull final ApiException base) {
        Objects.requireNonNull(base);
```

**Review by baywet — APPROVED** [review]

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+        Objects.requireNonNull(base);
+        value = new ApiException(base.getMessage(), base.getCause());
+    }
+
+    /**
+     * Assign the message to the builder
+     * @param message The message to be attached to this ApiException.
+     * @return The builder object.
+     */
+    public ApiExceptionBuilder withMessage(@Nonnull String message) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:32]:
```suggestion
    @Nonnull
    public ApiExceptionBuilder withMessage(@Nonnull String message) {
```

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 8]
```diff
@@ -0,0 +1,92 @@
...
+        }
+        return this;
+    }
+
+    /**
+     * Assign the Throwable cause of the Exception to the builder
+     * @param exception The Throwable to be used as Cause for this ApiException.
+     * @return The builder object.
+     */
+    public ApiExceptionBuilder withThrowable(@Nonnull Throwable exception) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:47]:
```suggestion
    @Nonnull
    public ApiExceptionBuilder withThrowable(@Nonnull Throwable exception) {
```

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 9]
```diff
@@ -0,0 +1,92 @@
...
+        }
+        return this;
+    }
+
+    /**
+     * Assign the response status code to the builder
+     * @param responseStatusCode an int representing the response status code.
+     * @return The builder object.
+     */
+    public ApiExceptionBuilder withResponseStatusCode(int responseStatusCode) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:62]:
```suggestion
    @Nonnull
    public ApiExceptionBuilder withResponseStatusCode(int responseStatusCode) {
```

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+        value.setResponseStatusCode(responseStatusCode);
+        return this;
+    }
+
+    /**
+     * Assign the response headers to the builder
+     * @param responseHeaders the response headers to be added to this ApiException.
+     * @return The builder object.
+     */
+    public ApiExceptionBuilder withResponseHeaders(@Nonnull ResponseHeaders responseHeaders) {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:75]:
```suggestion
    @Nonnull
    public ApiExceptionBuilder withResponseHeaders(@Nonnull ResponseHeaders responseHeaders) {
```

File: components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java [hunk 11]
```diff
@@ -0,0 +1,92 @@
...
+        }
+        value.setResponseHeaders(responseHeaders);
+        return this;
+    }
+
+    /**
+     * Build and return an instance of ApiException
+     * @return The built ApiException.
+     */
+    public ApiException build() {
```
Comment (baywet) [inline components/abstractions/src/main/java/com/microsoft/kiota/ApiExceptionBuilder.java:87]:
```suggestion
    @Nonnull
    public ApiException build() {
```

**Review by baywet — CHANGES_REQUESTED** [review]

**Review by baywet — APPROVED** [review]
